name: Tự động gửi thông báo thời tiết

on:
  schedule:
    - cron: '0 15 * * *'
  workflow_dispatch:

jobs:
  weather-bot:
    runs-on: ubuntu-latest
    
    steps:
      - name: Lấy code từ GitHub
        uses: actions/checkout@v4
      
      - name: Cài đặt Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Cài đặt thư viện
        run: |
          pip install requests
      
      - name: Tạo file JSON thời tiết
        run: python tao_json_thoitiet.py
      
      - name: Gửi thông báo
        env:
          PUSHBULLET_TOKEN: ${{ secrets.PUSHBULLET_TOKEN }}
        run: python gui_tu_json.py