name: Robot Tu Dong Don Dep
on:
  push:
    branches: [ main, master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Chay Robot
        run: python organize_data.py
      - name: Luu thay doi
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Robot-Manager"
          git add SUC_KHOE/ CHAM_SOC_GIA_DINH/ LAP_TRINH_ROBOT/  # Thêm cụ thể các thư mục
          git commit -m "Robot da don dep xong [skip ci]" || exit 0
          git push

